### PR TITLE
Resolve Redis incr expired key will make ttl -2

### PR DESCRIPTION
**Pull request by fxm5547**
Resolve Redis incr expired key will make ttl -2.
This Happen occasionally.

### CODE REVIEW

**Comment by nikolaposa** [comment]
I think that this change affects semantics and behavior of the `increment()` method significantly. Also, when do you think this can happen knowing the context in which method itself is used, so within the parent `hit()` method, and only when `$current` is set?

**Comment by fxm5547** [comment]
@nikolaposa This happen in our production environment. We spent lots of time to locate this bug after read this: https://redis.io/commands/incr. 
>If the key does not exist, it is set to 0 before performing the operation.

**Comment by fxm5547** [comment]
@nikolaposa Can you use other implement to resolve this bug?

**Comment by nikolaposa** [comment]
@fxm5547 I'm aware that `INCR` defaults to 0 if the key does not exist, but like I've said, if you take a look at the overall `hit()` implementation (https://github.com/nikolaposa/rate-limit/blob/master/src/AbstractRateLimiter.php#L62), it prevents such a situation from happening. 

Do you have some sample code to show that reproduces this issue?

**Comment by fxm5547** [comment]
@nikolaposa This Happen occasionally. Only when incr command is executing, the key expired. 
This probability of occurrence is very low, but it happend!  today, My friend told me that he has also encountered this situation.

**Comment by fxm5547** [comment]
`hit()` cant not  prevent such a situation from happening.

**Comment by nikolaposa** [comment]
@fxm5547 I understand that, and if so, beside the code you provided, you should also write appropriate test to cover that particular use case. 

What concerns me about this fix is that the behavior of the internal `increment()` method changes significantly and becomes complex. I would rather try to fix that at a different level, somewhere around here: https://github.com/nikolaposa/rate-limit/blob/master/src/AbstractRateLimiter.php#L75.

**Comment by fxm5547** [comment]
@nikolaposa I appreciate your fixing it. Thank you!

**Comment by nikolaposa** [comment]
@fxm5547 I'll try to investigate this in more detail when I find some time, thanks for reporting anyway. Perhaps you can open an [issue](https://github.com/nikolaposa/rate-limit/issues) that reports this problem.

**Pull request closed without merging**
